---
- name: "Manage Cloudflare DNS record"
  cloudflare_dns:
    account_email: "{{ item.email | default(cloudflare_dns_account_email) }}"
    account_api_token: "{{ item.token | default(cloudflare_dns_account_api_token) }}"
    zone: "{{ item.zone | default(cloudflare_dns_zone) }}"
    record: "{{ item.name }}"
    type: "{{ item.type | default('A') }}"
    ttl: "{{ item.ttl | default(1) }}"
    proxied: "{{ item.proxied | default('no') }}"
    priority: "{{ item.priority | default(1) }}"
    solo:  "{{  item.solo | default('yes' if item.state is not defined or item.state == 'present' else 'no') }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  delegate_to: localhost
  loop: "{{ cloudflare_dns_all_records }}"
  tags: ["cloudflare_dns", "config"]
