---
- name: Delete DNS records
  hosts: localhost
  tasks:
    - name: Include get authorized_keys
      include: ../resources/playbooks/get_zone_records.yml
    - name: Delete zone record
      uri:
        url: "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records/{{ item.id }}"
        method: DELETE
        headers:
          X-Auth-Email: "{{ cloudflare_dns_account_email }}"
          X-Auth-Key: "{{ cloudflare_dns_account_api_token }}"
      loop: "{{ get_zone_records_result.json.result }}"
